#!/usr/bin/sh

sxhkd &
polybar &

bspc monitor -d I II III IV V

nitrogen --restore &
picom --experimental-backends -b


bspc config border_width         0
bspc config window_gap           10
bspc config focused_border_color  "#d466e0"

bspc config split_ratio          0.62
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
